import pandas as pd
from dao import pr14BaseDao
from util import validations


def upload_data_PR14_base(cli_args):
    input_file_name = cli_args.input_file
    pd.set_option("display.precision", 18)

    df = pd.read_excel(input_file_name, sheet_name='PC list', usecols="A:DB,DU:DZ,EC:EJ", skiprows=[0])
    df.columns = ['unique_id', 'company_type', 'company', 'element_name', 'element_acronym', 'outcome', 'pc_ref',
                  'annex',
                  'performance_commitment', 'odi_type', 'odi_form', 'in_period_odi', 'vanilla_odi', 'primary_category',
                  'pc_unit', 'pc_unit_description', 'decimal_places', 'direction_of_improving_performance',
                  'starting_level_pr14_fd_2014_15', 'pcl_2015_16', 'pcl_2016_17', 'pcl_2017_18', 'pcl_2018_19',
                  'pcl_2019_20', 'PR14_comparative_drinking_water_compliance',
                  'PR14_comparative_water_quality_contacts',
                  'PR14_comparative_supply_interruptions_3_hours', 'PR14_comparative_pollution_incidents_cat_3',
                  'PR14_comparative_internal_sewer_flooding',
                  'scheme_specific_factor', 'asset_health', 'nep', 'aim', 'no_of_sub_measures', 'financial_odi_2015_16',
                  'financial_odi_2016_17', 'financial_odi_2017_18', 'financial_odi_2018_19', 'financial_odi_2019_20',
                  'underp_payment_collar_2015_16', 'underp_payment_collar_2016_17', 'underp_payment_collar_2017_18',
                  'underp_payment_collar_2018_19', 'underp_payment_collar_2019_20', 'underp_payment_deadband_2015_16',
                  'underp_payment_deadband_2016_17', 'underp_payment_deadband_2017_18',
                  'underp_payment_deadband_2018_19',
                  'underp_payment_deadband_2019_20', 'outp_payment_deadband_2015_16', 'outp_payment_deadband_2016_17',
                  'outp_payment_deadband_2017_18', 'outp_payment_deadband_2018_19', 'outp_payment_deadband_2019_20',
                  'outp_payment_cap_2015_16', 'outp_payment_cap_2016_17', 'outp_payment_cap_2017_18',
                  'outp_payment_cap_2018_19', 'outp_payment_cap_2019_20', 'underp_payment1_incentive_rate_gbpm_column',
                  'underp_payment2_incentive_rate_gbpm_column', 'underp_payment3_incentive_rate_gbpm_column',
                  'underp_payment4_incentive_rate_gbpm_column', 'outp_payment1_incentive_rate_gbpm_column',
                  'outp_payment2_incentive_rate_gbpm_column', 'standard_odi_operand', 'standard_odi_operand_note',
                  'performance_level_actual_2014_15', 'performance_level_actual_2015_16', 'pcl_met_2015_16',
                  'outp_payment_or_underp_payment_in_period_odis_2015_16',
                  'outp_payment_or_underp_payment_in_period_odis_gbpm_2015_16',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_2015_16',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_gbpm_2015_16',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2015_16',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2015_16',
                  'performance_level_actual_2016_17', 'pcl_met_2016_17',
                  'outp_payment_or_underp_payment_in_period_odis_2016_17',
                  'outp_payment_or_underp_payment_in_period_odis_gbpm_2016_17',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_2016_17',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_gbpm_2016_17',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2016_17',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2016_17',
                  'performance_level_actual_2017_18', 'pcl_met_2017_18',
                  'outp_payment_or_underp_payment_in_period_odis_2017_18',
                  'outp_payment_or_underp_payment_in_period_odis_gbpm_2017_18',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_2017_18',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_gbpm_2017_18',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2017_18',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2017_18',
                  'performance_level_actual_2018_19', 'pcl_met_2018_19',
                  'outp_payment_or_underp_payment_in_period_odis_2018_19',
                  'outp_payment_or_underp_payment_in_period_odis_gbpm_2018_19',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_2018_19',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_gbpm_2018_19',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2018_19',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2018_19',
                  'performance_level_actual_2019_20', 'pcl_met_2019_20',
                  'outp_payment_or_underp_payment_in_period_odis_2019_20',
                  'outp_payment_or_underp_payment_in_period_odis_gbpm_2019_20',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_2019_20',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_2019_20',
                  'performance_level_actual_estimates_2019_20', 'pcl_met_estimates_2019_20',
                  'outp_payment_or_underp_payment_in_period_odis_estimates_2019_20',
                  'outp_payment_or_underp_payment_in_period_odis_gbpm_estimates_2019_20',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_estimates_2019_20',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_estimates_2019_20',
                  'price_control_allocation_water_resources', 'price_control_allocation_water_network_plus',
                  'price_control_allocation_wastewater_network_plus', 'price_control_allocation_bioresources_sludge',
                  'price_control_allocation_residential_retail', 'price_control_allocation_business_retail',
                  'price_control_allocation_direct_procurement_for_customers', 'price_control_allocation_dummy_control']
    df = df.astype({'unique_id': 'object', 'company_type': 'object', 'company': 'object', 'element_name': 'object',
                    'element_acronym': 'object', 'outcome': 'object', 'pc_ref': 'object', 'annex': 'object',
                    'performance_commitment': 'object', 'odi_type': 'object', 'odi_form': 'object',
                    'in_period_odi': 'object', 'vanilla_odi': 'object', 'primary_category': 'object',
                    'pc_unit': 'object',
                    'pc_unit_description': 'object', 'decimal_places': 'object',
                    'direction_of_improving_performance': 'object', 'starting_level_pr14_fd_2014_15': 'object',
                    'pcl_2015_16': 'object', 'pcl_2016_17': 'object', 'pcl_2017_18': 'object', 'pcl_2018_19': 'object',
                    'pcl_2019_20': 'object', 'PR14_comparative_drinking_water_compliance': 'object',
                    'PR14_comparative_water_quality_contacts': 'object',
                    'PR14_comparative_supply_interruptions_3_hours': 'object',
                    'PR14_comparative_pollution_incidents_cat_3': 'object',
                    'PR14_comparative_internal_sewer_flooding': 'object',
                    'scheme_specific_factor': 'object', 'asset_health': 'object', 'nep': 'object', 'aim': 'object',
                    'no_of_sub_measures': 'int64', 'financial_odi_2015_16': 'object', 'financial_odi_2016_17': 'object',
                    'financial_odi_2017_18': 'object', 'financial_odi_2018_19': 'object',
                    'financial_odi_2019_20': 'object',
                    'underp_payment_collar_2015_16': 'object', 'underp_payment_collar_2016_17': 'object',
                    'underp_payment_collar_2017_18': 'object', 'underp_payment_collar_2018_19': 'object',
                    'underp_payment_collar_2019_20': 'object', 'underp_payment_deadband_2015_16': 'object',
                    'underp_payment_deadband_2016_17': 'object', 'underp_payment_deadband_2017_18': 'object',
                    'underp_payment_deadband_2018_19': 'object', 'underp_payment_deadband_2019_20': 'object',
                    'outp_payment_deadband_2015_16': 'object', 'outp_payment_deadband_2016_17': 'object',
                    'outp_payment_deadband_2017_18': 'object', 'outp_payment_deadband_2018_19': 'object',
                    'outp_payment_deadband_2019_20': 'object', 'outp_payment_cap_2015_16': 'object',
                    'outp_payment_cap_2016_17': 'object', 'outp_payment_cap_2017_18': 'object',
                    'outp_payment_cap_2018_19': 'object', 'outp_payment_cap_2019_20': 'object',
                    'underp_payment1_incentive_rate_gbpm_column': 'object',
                    'underp_payment2_incentive_rate_gbpm_column': 'object',
                    'underp_payment3_incentive_rate_gbpm_column': 'object',
                    'underp_payment4_incentive_rate_gbpm_column': 'object',
                    'outp_payment1_incentive_rate_gbpm_column': 'object',
                    'outp_payment2_incentive_rate_gbpm_column': 'object',
                    'standard_odi_operand': 'object', 'standard_odi_operand_note': 'object',
                    'performance_level_actual_2014_15': 'object', 'performance_level_actual_2015_16': 'object',
                    'pcl_met_2015_16': 'object', 'outp_payment_or_underp_payment_in_period_odis_2015_16': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_gbpm_2015_16': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_2015_16': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_gbpm_2015_16': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2015_16': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2015_16': 'object',
                    'performance_level_actual_2016_17': 'object', 'pcl_met_2016_17': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_2016_17': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_gbpm_2016_17': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_2016_17': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_gbpm_2016_17': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2016_17': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2016_17': 'object',
                    'performance_level_actual_2017_18': 'object', 'pcl_met_2017_18': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_2017_18': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_gbpm_2017_18': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_2017_18': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_gbpm_2017_18': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2017_18': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2017_18': 'object',
                    'performance_level_actual_2018_19': 'object', 'pcl_met_2018_19': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_2018_19': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_gbpm_2018_19': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_2018_19': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_gbpm_2018_19': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2018_19': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2018_19': 'object',
                    'performance_level_actual_2019_20': 'object', 'pcl_met_2019_20': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_2019_20': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_gbpm_2019_20': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_2019_20': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_2019_20': 'object',
                    'performance_level_actual_estimates_2019_20': 'object', 'pcl_met_estimates_2019_20': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_estimates_2019_20': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_gbpm_estimates_2019_20': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_estimates_2019_20': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_estimates_2019_20': 'object',
                    'price_control_allocation_water_resources': 'float64',
                    'price_control_allocation_water_network_plus': 'float64',
                    'price_control_allocation_wastewater_network_plus': 'float64',
                    'price_control_allocation_bioresources_sludge': 'float64',
                    'price_control_allocation_residential_retail': 'float64',
                    'price_control_allocation_business_retail': 'float64',
                    'price_control_allocation_direct_procurement_for_customers': 'float64',
                    'price_control_allocation_dummy_control': 'float64'})
    listofPR14columns = []
    for column in df:
        listofPR14columns.append(column)
    for i in listofPR14columns:
        df[i] = validations.replace_spaces(df, i)
        df[i] = validations.replace_dashes_with_nan(df, i)
        df[i] = validations.replace_null_with_None(df, i)
        if i in ['PR14_comparative_drinking_water_compliance', 'PR14_comparative_water_quality_contacts',
                 'PR14_comparative_supply_interruptions_3_hours',
                 'PR14_comparative_pollution_incidents_cat_3', 'PR14_comparative_internal_sewer_flooding',
                 'scheme_specific_factor', 'asset_health',
                 'nep',
                 'aim']:
            df[i] = validations.replace_yes_with_true(df, i)
        if i in ['underp_payment1_incentive_rate_gbpm_column', 'underp_payment2_incentive_rate_gbpm_column',
                 'underp_payment3_incentive_rate_gbpm_column', 'underp_payment4_incentive_rate_gbpm_column',
                 'outp_payment1_incentive_rate_gbpm_column', 'outp_payment2_incentive_rate_gbpm_column']:
            validations.is_numeric_and_only_numeric(df, i)

        if i == 'company':
            df[i] = validations.change_company_to_UUW(df)
    df = df.rename(
        columns={'onlynumeric_underp_payment1_incentive_rate_gbpm_column': 'underp_payment1_incentive_rate_gbpm',
                 'onlynumeric_underp_payment2_incentive_rate_gbpm_column': 'underp_payment2_incentive_rate_gbpm',
                 'onlynumeric_underp_payment3_incentive_rate_gbpm_column': 'underp_payment3_incentive_rate_gbpm',
                 'onlynumeric_underp_payment4_incentive_rate_gbpm_column': 'underp_payment4_incentive_rate_gbpm',
                 'onlynumeric_outp_payment1_incentive_rate_gbpm_column': 'outp_payment1_incentive_rate_gbpm',
                 'onlynumeric_outp_payment2_incentive_rate_gbpm_column': 'outp_payment2_incentive_rate_gbpm',
                 'notes_underp_payment1_incentive_rate_gbpm_column': 'notes_underp_payment1_incentive_rate_gbpm',
                 'notes_underp_payment2_incentive_rate_gbpm_column': 'notes_underp_payment2_incentive_rate_gbpm',
                 'notes_underp_payment3_incentive_rate_gbpm_column': 'notes_underp_payment3_incentive_rate_gbpm',
                 'notes_underp_payment4_incentive_rate_gbpm_column': 'notes_underp_payment4_incentive_rate_gbpm',
                 'notes_outp_payment1_incentive_rate_gbpm_column': 'notes_outp_payment1_incentive_rate_gbpm',
                 'notes_outp_payment2_incentive_rate_gbpm_column': 'notes_outp_payment2_incentive_rate_gbpm',
                 })
    df.drop(columns=['isnumeric_underp_payment1_incentive_rate_gbpm_column',
                     'isnumeric_underp_payment2_incentive_rate_gbpm_column',
                     'isnumeric_underp_payment3_incentive_rate_gbpm_column',
                     'isnumeric_underp_payment4_incentive_rate_gbpm_column',
                     'isnumeric_outp_payment1_incentive_rate_gbpm_column',
                     'isnumeric_outp_payment2_incentive_rate_gbpm_column'], axis=1, inplace=True)

    if not cli_args.test_run:
        pr14BaseDao.insert_pr14_data_in_table(df)
