import pandas as pd
from util import validations
from util import dbUtils


# Main program
def upload_data():
    pd.set_option("display.precision", 18)

    # Read excel for PR14 and create csv with columns needed
    df = pd.read_excel(r'../resources/AnnesPR14.xlsx', sheet_name='PC list', usecols="A:DB,DU:DZ,EC:EJ", skiprows=[0])
    df.columns = ['unique_id', 'company_type', 'company', 'element_name', 'element_acronym', 'outcome', 'pc_ref',
                  'annex',
                  'performance_commitment', 'odi_type', 'odi_form', 'in_period_odi', 'vanilla_odi', 'primary_category',
                  'pc_unit', 'pc_unit_description', 'decimal_places', 'direction_of_improving_performance',
                  'starting_level_pr14_fd_2014_15', 'pcl_2015_16', 'pcl_2016_17', 'pcl_2017_18', 'pcl_2018_19',
                  'pcl_2019_20', 'drinking_water_quality_compliance', 'water_quality_contacts',
                  'supply_interruptions_3_hours', 'pollution_incidents_cat_3', 'internal_sewer_flooding',
                  'scheme_specific_factor', 'asset_health', 'nep', 'aim', 'no_of_sub_measures', 'financial_odi_2015_16',
                  'financial_odi_2016_17', 'financial_odi_2017_18', 'financial_odi_2018_19', 'financial_odi_2019_20',
                  'underp_payment_collar_2015_16', 'underp_payment_collar_2016_17', 'underp_payment_collar_2017_18',
                  'underp_payment_collar_2018_19', 'underp_payment_collar_2019_20', 'underp_payment_deadband_2015_16',
                  'underp_payment_deadband_2016_17', 'underp_payment_deadband_2017_18',
                  'underp_payment_deadband_2018_19',
                  'underp_payment_deadband_2019_20', 'outp_payment_deadband_2015_16', 'outp_payment_deadband_2016_17',
                  'outp_payment_deadband_2017_18', 'outp_payment_deadband_2018_19', 'outp_payment_deadband_2019_20',
                  'outp_payment_cap_2015_16', 'outp_payment_cap_2016_17', 'outp_payment_cap_2017_18',
                  'outp_payment_cap_2018_19', 'outp_payment_cap_2019_20', 'underp_payment1_incentive_rate_gbpm',
                  'underp_payment2_incentive_rate_gbpm', 'underp_payment3_incentive_rate_gbpm',
                  'underp_payment4_incentive_rate_gbpm', 'outp_payment1_incentive_rate_gbpm',
                  'outp_payment2_incentive_rate_gbpm', 'standard_odi_operand', 'standard_odi_operand_note',
                  'performance_level_actual_2014_15', 'performance_level_actual_2015_16', 'pcl_met_2015_16',
                  'outp_payment_or_underp_payment_in_period_odis_2015_16',
                  'outp_payment_or_underp_payment_in_period_odis_gbpm_2015_16',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_2015_16',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_gbpm_2015_16',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2015_16',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2015_16',
                  'performance_level_actual_2016_17', 'pcl_met_2016_17',
                  'outp_payment_or_underp_payment_in_period_odis_2016_17',
                  'outp_payment_or_underp_payment_in_period_odis_gbpm_2016_17',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_2016_17',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_gbpm_2016_17',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2016_17',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2016_17',
                  'performance_level_actual_2017_18', 'pcl_met_2017_18',
                  'outp_payment_or_underp_payment_in_period_odis_2017_18',
                  'outp_payment_or_underp_payment_in_period_odis_gbpm_2017_18',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_2017_18',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_gbpm_2017_18',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2017_18',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2017_18',
                  'performance_level_actual_2018_19', 'pcl_met_2018_19',
                  'outp_payment_or_underp_payment_in_period_odis_2018_19',
                  'outp_payment_or_underp_payment_in_period_odis_gbpm_2018_19',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_2018_19',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_gbpm_2018_19',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2018_19',
                  'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2018_19',
                  'performance_level_actual_2019_20', 'pcl_met_2019_20',
                  'outp_payment_or_underp_payment_in_period_odis_2019_20',
                  'outp_payment_or_underp_payment_in_period_odis_gbpm_2019_20',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_2019_20',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_2019_20',
                  'performance_level_actual_estimates_2019_20', 'pcl_met_estimates_2019_20',
                  'outp_payment_or_underp_payment_in_period_odis_estimates_2019_20',
                  'outp_payment_or_underp_payment_in_period_odis_gbpm_estimates_2019_20',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_estimates_2019_20',
                  'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_estimates_2019_20',
                  'price_control_allocation_water_resources', 'price_control_allocation_water_network_plus',
                  'price_control_allocation_wastewater_network_plus', 'price_control_allocation_bioresources_sludge',
                  'price_control_allocation_residential_retail', 'price_control_allocation_business_retail',
                  'price_control_allocation_direct_procurement_for_customers', 'price_control_allocation_dummy_control']
    df = df.astype({'unique_id': 'object', 'company_type': 'object', 'company': 'object', 'element_name': 'object',
                    'element_acronym': 'object', 'outcome': 'object', 'pc_ref': 'object', 'annex': 'object',
                    'performance_commitment': 'object', 'odi_type': 'object', 'odi_form': 'object',
                    'in_period_odi': 'object', 'vanilla_odi': 'object', 'primary_category': 'object',
                    'pc_unit': 'object',
                    'pc_unit_description': 'object', 'decimal_places': 'object',
                    'direction_of_improving_performance': 'object', 'starting_level_pr14_fd_2014_15': 'object',
                    'pcl_2015_16': 'object', 'pcl_2016_17': 'object', 'pcl_2017_18': 'object', 'pcl_2018_19': 'object',
                    'pcl_2019_20': 'object', 'drinking_water_quality_compliance': 'object',
                    'water_quality_contacts': 'object', 'supply_interruptions_3_hours': 'object',
                    'pollution_incidents_cat_3': 'object', 'internal_sewer_flooding': 'object',
                    'scheme_specific_factor': 'object', 'asset_health': 'object', 'nep': 'object', 'aim': 'object',
                    'no_of_sub_measures': 'int64', 'financial_odi_2015_16': 'object', 'financial_odi_2016_17': 'object',
                    'financial_odi_2017_18': 'object', 'financial_odi_2018_19': 'object',
                    'financial_odi_2019_20': 'object',
                    'underp_payment_collar_2015_16': 'object', 'underp_payment_collar_2016_17': 'object',
                    'underp_payment_collar_2017_18': 'object', 'underp_payment_collar_2018_19': 'object',
                    'underp_payment_collar_2019_20': 'object', 'underp_payment_deadband_2015_16': 'object',
                    'underp_payment_deadband_2016_17': 'object', 'underp_payment_deadband_2017_18': 'object',
                    'underp_payment_deadband_2018_19': 'object', 'underp_payment_deadband_2019_20': 'object',
                    'outp_payment_deadband_2015_16': 'object', 'outp_payment_deadband_2016_17': 'object',
                    'outp_payment_deadband_2017_18': 'object', 'outp_payment_deadband_2018_19': 'object',
                    'outp_payment_deadband_2019_20': 'object', 'outp_payment_cap_2015_16': 'object',
                    'outp_payment_cap_2016_17': 'object', 'outp_payment_cap_2017_18': 'object',
                    'outp_payment_cap_2018_19': 'object', 'outp_payment_cap_2019_20': 'object',
                    'underp_payment1_incentive_rate_gbpm': 'object', 'underp_payment2_incentive_rate_gbpm': 'object',
                    'underp_payment3_incentive_rate_gbpm': 'object', 'underp_payment4_incentive_rate_gbpm': 'object',
                    'outp_payment1_incentive_rate_gbpm': 'object', 'outp_payment2_incentive_rate_gbpm': 'object',
                    'standard_odi_operand': 'float64', 'standard_odi_operand_note': 'object',
                    'performance_level_actual_2014_15': 'object', 'performance_level_actual_2015_16': 'object',
                    'pcl_met_2015_16': 'object', 'outp_payment_or_underp_payment_in_period_odis_2015_16': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_gbpm_2015_16': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_2015_16': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_gbpm_2015_16': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2015_16': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2015_16': 'object',
                    'performance_level_actual_2016_17': 'object', 'pcl_met_2016_17': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_2016_17': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_gbpm_2016_17': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_2016_17': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_gbpm_2016_17': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2016_17': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2016_17': 'object',
                    'performance_level_actual_2017_18': 'object', 'pcl_met_2017_18': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_2017_18': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_gbpm_2017_18': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_2017_18': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_gbpm_2017_18': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2017_18': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2017_18': 'object',
                    'performance_level_actual_2018_19': 'object', 'pcl_met_2018_19': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_2018_19': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_gbpm_2018_19': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_2018_19': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_gbpm_2018_19': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2018_19': 'object',
                    'total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2018_19': 'object',
                    'performance_level_actual_2019_20': 'object', 'pcl_met_2019_20': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_2019_20': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_gbpm_2019_20': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_2019_20': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_2019_20': 'object',
                    'performance_level_actual_estimates_2019_20': 'object', 'pcl_met_estimates_2019_20': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_estimates_2019_20': 'object',
                    'outp_payment_or_underp_payment_in_period_odis_gbpm_estimates_2019_20': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_estimates_2019_20': 'object',
                    'notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_estimates_2019_20': 'object',
                    'price_control_allocation_water_resources': 'float64',
                    'price_control_allocation_water_network_plus': 'float64',
                    'price_control_allocation_wastewater_network_plus': 'float64',
                    'price_control_allocation_bioresources_sludge': 'float64',
                    'price_control_allocation_residential_retail': 'float64',
                    'price_control_allocation_business_retail': 'float64',
                    'price_control_allocation_direct_procurement_for_customers': 'float64',
                    'price_control_allocation_dummy_control': 'float64'})
    validations.replacespaces(df)
    mylist = []
    for column in df:
        mylist.append(column)
    for i in mylist:
        df[i] = validations.replacedashes(df, i)
        df[i] = validations.replacenullvalues(df, i)
        if i in ['drinking_water_quality_compliance', 'water_quality_contacts', 'supply_interruptions_3_hours',
                 'pollution_incidents_cat_3', 'internal_sewer_flooding', 'scheme_specific_factor', 'asset_health',
                 'nep',
                 'aim']:
            df[i] = validations.replaceyeswithtrues(df, i)
        if i in ['underp_payment1_incentive_rate_gbpm', 'underp_payment2_incentive_rate_gbpm',
                 'underp_payment3_incentive_rate_gbpm', 'underp_payment4_incentive_rate_gbpm',
                 'outp_payment1_incentive_rate_gbpm', 'outp_payment2_incentive_rate_gbpm']:
            validations.isnumericandonlynumeric(df, i)

    # Read excel for PR19 and create csv with columns needed
    df1 = pd.read_excel(r'../resources/Pauls_latest_PR19.xlsx',
                        sheet_name='App1', usecols="A,C:D,F:P,R:AF,AQ:AU,BL:DE",
                        skiprows=[0, 1, 2, 3, 4])
    df1.columns = ['company', 'unique_id', 'outcome', 'pc_ref', 'performance_commitment', 'pc_short_description',
                   'price_control_allocation_water_resources', 'price_control_allocation_water_network_plus',
                   'price_control_allocation_wastewater_network_plus', 'price_control_allocation_bioresources_sludge',
                   'price_control_allocation_residential_retail', 'price_control_allocation_business_retail',
                   'price_control_allocation_direct_procurement_for_customers',
                   'price_control_allocation_dummy_control',
                   'odi_type', 'odi_form', 'odi_timing', 'primary_category', 'pc_unit', 'pc_unit_description',
                   'decimal_places', 'direction_of_improving_performance',
                   'common_and_comparable_bespoke_performance_commitment', 'special_cost_factor',
                   'scheme_specific_factor',
                   'asset_health', 'nep', 'aim', 'customers_relative_priority', 'pcl_2020_21', 'pcl_2021_22',
                   'pcl_2022_23',
                   'pcl_2023_24', 'pcl_2024_25', 'financial_odi_2020_21', 'financial_odi_2021_22',
                   'financial_odi_2022_23',
                   'financial_odi_2023_24', 'financial_odi_2024_25', 'enhanced_underp_payment_collar_2020_21',
                   'enhanced_underp_payment_collar_2021_22', 'enhanced_underp_payment_collar_2022_23',
                   'enhanced_underp_payment_collar_2023_24', 'enhanced_underp_payment_collar_2024_25',
                   'standard_underp_payment_collar_2020_21', 'standard_underp_payment_collar_2021_22',
                   'standard_underp_payment_collar_2022_23', 'standard_underp_payment_collar_2023_24',
                   'standard_underp_payment_collar_2024_25', 'underp_payment_deadband_2020_21',
                   'underp_payment_deadband_2021_22', 'underp_payment_deadband_2022_23',
                   'underp_payment_deadband_2023_24',
                   'underp_payment_deadband_2024_25', 'outp_payment_deadband_2020_21', 'outp_payment_deadband_2021_22',
                   'outp_payment_deadband_2022_23', 'outp_payment_deadband_2023_24', 'outp_payment_deadband_2024_25',
                   'standard_outp_payment_cap_2020_21', 'standard_outp_payment_cap_2021_22',
                   'standard_outp_payment_cap_2022_23', 'standard_outp_payment_cap_2023_24',
                   'standard_outp_payment_cap_2024_25', 'enhanced_outp_payment_cap_2020_21',
                   'enhanced_outp_payment_cap_2021_22', 'enhanced_outp_payment_cap_2022_23',
                   'enhanced_outp_payment_cap_2023_24', 'enhanced_outp_payment_cap_2024_25',
                   'underp_payment_incentive_standard_underp_payment1_tier2_where_tiers_apply',
                   'underp_payment_incentive_standard_underp_payment2_tier1_where_tiers_apply',
                   'underp_payment_incentive_standard_underp_payment3_tier3_where_tiers_apply',
                   'underp_payment_incentive_enhanced_underp_payment',
                   'outp_payment_incentive_standard_outp_payment1_tier2_where_tiers_apply',
                   'outp_payment_incentive_standard_outp_payment2_tier1_where_tiers_apply',
                   'outp_payment_incentive_standard_outp_payment3_tier3_where_tiers_apply',
                   'outp_payment_incentive_enhanced_outp_payment', 'standard_odi_cal', 'standard_odi_operand',
                   'standard_odi_operand_note']
    df1 = df1.astype({'company': 'object', 'unique_id': 'object', 'outcome': 'object', 'pc_ref': 'object',
                      'performance_commitment': 'object', 'pc_short_description': 'object',
                      'price_control_allocation_water_resources': 'float64',
                      'price_control_allocation_water_network_plus': 'float64',
                      'price_control_allocation_wastewater_network_plus': 'float64',
                      'price_control_allocation_bioresources_sludge': 'float64',
                      'price_control_allocation_residential_retail': 'float64',
                      'price_control_allocation_business_retail': 'float64',
                      'price_control_allocation_direct_procurement_for_customers': 'float64',
                      'price_control_allocation_dummy_control': 'float64',
                      'odi_type': 'object', 'odi_form': 'object', 'odi_timing': 'object', 'primary_category': 'object',
                      'pc_unit': 'object', 'pc_unit_description': 'object',
                      'decimal_places': 'object', 'direction_of_improving_performance': 'object',
                      'common_and_comparable_bespoke_performance_commitment': 'object', 'special_cost_factor': 'object',
                      'scheme_specific_factor': 'object',
                      'asset_health': 'object', 'nep': 'object', 'aim': 'object',
                      'customers_relative_priority': 'object',
                      'pcl_2020_21': 'object', 'pcl_2021_22': 'object', 'pcl_2022_23': 'object',
                      'pcl_2023_24': 'object', 'pcl_2024_25': 'object', 'financial_odi_2020_21': 'object',
                      'financial_odi_2021_22': 'object', 'financial_odi_2022_23': 'object',
                      'financial_odi_2023_24': 'object', 'financial_odi_2024_25': 'object',
                      'enhanced_underp_payment_collar_2020_21': 'object',
                      'enhanced_underp_payment_collar_2021_22': 'object',
                      'enhanced_underp_payment_collar_2022_23': 'object',
                      'enhanced_underp_payment_collar_2023_24': 'object',
                      'enhanced_underp_payment_collar_2024_25': 'object',
                      'standard_underp_payment_collar_2020_21': 'object',
                      'standard_underp_payment_collar_2021_22': 'object',
                      'standard_underp_payment_collar_2022_23': 'object',
                      'standard_underp_payment_collar_2023_24': 'object',
                      'standard_underp_payment_collar_2024_25': 'object', 'underp_payment_deadband_2020_21': 'object',
                      'underp_payment_deadband_2021_22': 'object', 'underp_payment_deadband_2022_23': 'object',
                      'underp_payment_deadband_2023_24': 'object',
                      'underp_payment_deadband_2024_25': 'object', 'outp_payment_deadband_2020_21': 'object',
                      'outp_payment_deadband_2021_22': 'object',
                      'outp_payment_deadband_2022_23': 'object', 'outp_payment_deadband_2023_24': 'object',
                      'outp_payment_deadband_2024_25': 'object',
                      'standard_outp_payment_cap_2020_21': 'object', 'standard_outp_payment_cap_2021_22': 'object',
                      'standard_outp_payment_cap_2022_23': 'object', 'standard_outp_payment_cap_2023_24': 'object',
                      'standard_outp_payment_cap_2024_25': 'object', 'enhanced_outp_payment_cap_2020_21': 'object',
                      'enhanced_outp_payment_cap_2021_22': 'object', 'enhanced_outp_payment_cap_2022_23': 'object',
                      'enhanced_outp_payment_cap_2023_24': 'object', 'enhanced_outp_payment_cap_2024_25': 'object',
                      'underp_payment_incentive_standard_underp_payment1_tier2_where_tiers_apply': 'object',
                      'underp_payment_incentive_standard_underp_payment2_tier1_where_tiers_apply': 'object',
                      'underp_payment_incentive_standard_underp_payment3_tier3_where_tiers_apply': 'object',
                      'underp_payment_incentive_enhanced_underp_payment': 'object',
                      'outp_payment_incentive_standard_outp_payment1_tier2_where_tiers_apply': 'object',
                      'outp_payment_incentive_standard_outp_payment2_tier1_where_tiers_apply': 'object',
                      'outp_payment_incentive_standard_outp_payment3_tier3_where_tiers_apply': 'object',
                      'outp_payment_incentive_enhanced_outp_payment': 'object', 'standard_odi_cal': 'object',
                      'standard_odi_operand': 'object',
                      'standard_odi_operand_note': 'object'})
    validations.replacespaces(df1)
    mylist1 = []
    for column in df1:
        mylist1.append(column)
    for j in mylist1:
        df1[j] = validations.replacedashes(df1, j)
        df1[j] = validations.replacenullvalues(df1, j)
        if j in ['scheme_specific_factor', 'asset_health', 'nep', 'aim']:
            df1[j] = validations.replaceyeswithtrues(df1, j)
        if j in ['underp_payment_incentive_standard_underp_payment1_tier2_where_tiers_apply',
                 'underp_payment_incentive_standard_underp_payment2_tier1_where_tiers_apply',
                 'underp_payment_incentive_standard_underp_payment3_tier3_where_tiers_apply',
                 'underp_payment_incentive_enhanced_underp_payment',
                 'outp_payment_incentive_standard_outp_payment1_tier2_where_tiers_apply',
                 'outp_payment_incentive_standard_outp_payment2_tier1_where_tiers_apply',
                 'outp_payment_incentive_standard_outp_payment3_tier3_where_tiers_apply',
                 'outp_payment_incentive_enhanced_outp_payment']:
            validations.isnumericandonlynumeric(df1, j)

    # Read excel for PR14 Submeasures
    df2 = pd.read_excel(r'../resources/AnnesPR14.xlsx',
                        sheet_name='Sub-measures', usecols="A:BB,BK,BL,BG:BH,BM:BR", skiprows=[0, 1])
    df2.columns = ['unique_id', 'company_type', 'company', 'element_acronym', 'pc_ref', 'performance_commitment',
                   'odi_type', 'primary_category', 'pc_unit_description', 'starting_level_pr14_fd_2014_15',
                   'pcl_2015_16',
                   'pcl_2016_17', 'pcl_2017_18', 'pcl_2018_19', 'pcl_2019_20', 'sub_measure_id', 'sub_measure',
                   'sub_measure_category', 'sub_measure_weighting', 'pc_unit', 'decimal_places',
                   'submeasure_performace_level_reference_regulatory_output_during_2010_15',
                   'submeasure_performace_level_reference_expected_performance_by_2014_15',
                   'submeasure_performace_level_2015_16', 'submeasure_performace_level_2016_17',
                   'submeasure_performace_level_2017_18', 'submeasure_performace_level_2018_19',
                   'submeasure_performace_level_2019_20', 'submeasure_high_reference_regulatory_output_during_2010_15',
                   'submeasure_high_reference_expected_performance_by_2014_15', 'submeasure_high_2015_16',
                   'submeasure_high_2016_17', 'submeasure_high_2017_18', 'submeasure_high_2018_19',
                   'submeasure_high_2019_20', 'submeasure_low_reference_regulatory_output_during_2010_15',
                   'submeasure_low_reference_expected_performance_by_2014_15', 'submeasure_low_2015_16',
                   'submeasure_low_2016_17', 'submeasure_low_2017_18', 'submeasure_low_2018_19',
                   'submeasure_low_2019_20',
                   'failure_threshold_for_AMP6', 'actual_performance_level_pcs_submeasures_actual_2014_15',
                   'actual_performance_level_pcs_submeasures_actual_2015_16',
                   'actual_performance_level_pcs_submeasures_pcl_met_2015_16',
                   'actual_performance_level_pcs_submeasures_actual_2016_17',
                   'actual_performance_level_pcs_submeasures_pcl_met_2016_17',
                   'actual_performance_level_pcs_submeasures_actual_2017_18',
                   'actual_performance_level_pcs_submeasures_pcl_met_2017_18',
                   'actual_performance_level_pcs_submeasures_actual_2018_19',
                   'actual_performance_level_pcs_submeasures_pcl_met_2018_19',
                   'actual_performance_level_pcs_submeasures_actual_2019_20',
                   'actual_performance_level_pcs_submeasures_pcl_met_2019_20',
                   'actual_performance_level_pcs_submeasures_actual_estimate_2019_20',
                   'actual_performance_level_pcs_submeasures_pcl_met_estimate_2019_20',
                   'direction_of_improving_performance', 'comms_filter',
                   'actual_performance_compared_with_previous_actual_performance_2014_15_to_2015_16',
                   'actual_performance_compared_with_previous_actual_performance_2015_16_to_2016_17',
                   'actual_performance_compared_with_previous_actual_performance_2016_17_to_2017_18',
                   'actual_performance_compared_with_previous_actual_performance_2017_18_to_2018_19',
                   'actual_performance_compared_with_previous_actual_performance_2018_19_to_2019_20',
                   'actual_performance_compared_with_previous_actual_performance_2014_15_to_2016_17_amp_so_far']
    df2 = df2.astype({'unique_id': 'object', 'company_type': 'object', 'company': 'object', 'element_acronym': 'object',
                      'pc_ref': 'object', 'performance_commitment': 'object', 'odi_type': 'object',
                      'primary_category': 'object', 'pc_unit_description': 'object',
                      'starting_level_pr14_fd_2014_15': 'object', 'pcl_2015_16': 'object', 'pcl_2016_17': 'object',
                      'pcl_2017_18': 'object', 'pcl_2018_19': 'object', 'pcl_2019_20': 'object',
                      'sub_measure_id': 'object',
                      'sub_measure': 'object', 'sub_measure_category': 'object', 'sub_measure_weighting': 'object',
                      'pc_unit': 'object', 'decimal_places': 'object',
                      'submeasure_performace_level_reference_regulatory_output_during_2010_15': 'object',
                      'submeasure_performace_level_reference_expected_performance_by_2014_15': 'object',
                      'submeasure_performace_level_2015_16': 'object', 'submeasure_performace_level_2016_17': 'object',
                      'submeasure_performace_level_2017_18': 'object', 'submeasure_performace_level_2018_19': 'object',
                      'submeasure_performace_level_2019_20': 'object',
                      'submeasure_high_reference_regulatory_output_during_2010_15': 'object',
                      'submeasure_high_reference_expected_performance_by_2014_15': 'object',
                      'submeasure_high_2015_16': 'object', 'submeasure_high_2016_17': 'object',
                      'submeasure_high_2017_18': 'object', 'submeasure_high_2018_19': 'object',
                      'submeasure_high_2019_20': 'object',
                      'submeasure_low_reference_regulatory_output_during_2010_15': 'float64',
                      'submeasure_low_reference_expected_performance_by_2014_15': 'object',
                      'submeasure_low_2015_16': 'object', 'submeasure_low_2016_17': 'object',
                      'submeasure_low_2017_18': 'object', 'submeasure_low_2018_19': 'object',
                      'submeasure_low_2019_20': 'object', 'failure_threshold_for_AMP6': 'object',
                      'actual_performance_level_pcs_submeasures_actual_2014_15': 'object',
                      'actual_performance_level_pcs_submeasures_actual_2015_16': 'object',
                      'actual_performance_level_pcs_submeasures_pcl_met_2015_16': 'object',
                      'actual_performance_level_pcs_submeasures_actual_2016_17': 'object',
                      'actual_performance_level_pcs_submeasures_pcl_met_2016_17': 'object',
                      'actual_performance_level_pcs_submeasures_actual_2017_18': 'object',
                      'actual_performance_level_pcs_submeasures_pcl_met_2017_18': 'object',
                      'actual_performance_level_pcs_submeasures_actual_2018_19': 'object',
                      'actual_performance_level_pcs_submeasures_pcl_met_2018_19': 'object',
                      'actual_performance_level_pcs_submeasures_actual_2019_20': 'object',
                      'actual_performance_level_pcs_submeasures_pcl_met_2019_20': 'object',
                      'actual_performance_level_pcs_submeasures_actual_estimate_2019_20': 'object',
                      'actual_performance_level_pcs_submeasures_pcl_met_estimate_2019_20': 'object',
                      'direction_of_improving_performance': 'object', 'comms_filter': 'object',
                      'actual_performance_compared_with_previous_actual_performance_2014_15_to_2015_16': 'object',
                      'actual_performance_compared_with_previous_actual_performance_2015_16_to_2016_17': 'object',
                      'actual_performance_compared_with_previous_actual_performance_2016_17_to_2017_18': 'object',
                      'actual_performance_compared_with_previous_actual_performance_2017_18_to_2018_19': 'object',
                      'actual_performance_compared_with_previous_actual_performance_2018_19_to_2019_20': 'object',
                      'actual_performance_compared_with_previous_actual_performance_2014_15_to_2016_17_amp_so_far': 'object'})
    validations.replacespaces(df2)
    mylist2 = []
    for column in df2:
        mylist2.append(column)
    for k in mylist2:
        df2[k] = validations.replacedashes(df2, k)
        df2[k] = validations.replacenullvalues(df2, k)
        if k in ['actual_performance_level_pcs_submeasures_pcl_met_2015_16',
                 'actual_performance_level_pcs_submeasures_pcl_met_2016_17',
                 'actual_performance_level_pcs_submeasures_pcl_met_2017_18',
                 'actual_performance_level_pcs_submeasures_pcl_met_2018_19',
                 'actual_performance_level_pcs_submeasures_pcl_met_2019_20',
                 'actual_performance_level_pcs_submeasures_pcl_met_estimate_2019_20']:
            df2[k] = validations.replaceyeswithtrues(df2, k)

    conn = dbUtils.sqlserverconnection()
    schemanameused = dbUtils.schemacreation()
    cursor = conn.cursor()

    # Query for PR14 data upload
    cursor.execute(
        "SELECT * FROM information_schema.tables where table_schema ='" + schemanameused + "' and table_name = 'PR14FinalCSVcreatedbyPython'")
    queryforsubmeasuretablecheck = cursor.fetchone()
    if queryforsubmeasuretablecheck == None:
        print("Creating PR14FinalCSVcreatedbyPython table")
        cursor.execute(
            'CREATE TABLE ' + schemanameused + '.PR14FinalCSVcreatedbyPython(unique_id nvarchar(max),company_type nvarchar(max),company nvarchar(max),element_name nvarchar(max),element_acronym nvarchar(max),outcome nvarchar(max),pc_ref nvarchar(max),annex nvarchar(max),performance_commitment nvarchar(max),odi_type nvarchar(max),odi_form nvarchar(max),in_period_odi nvarchar(max),vanilla_odi nvarchar(max),primary_category nvarchar(max),pc_unit nvarchar(max),pc_unit_description nvarchar(max),decimal_places nvarchar(max),direction_of_improving_performance nvarchar(max),starting_level_pr14_fd_2014_15 nvarchar(max),pcl_2015_16 nvarchar(max),pcl_2016_17 nvarchar(max),pcl_2017_18 nvarchar(max),pcl_2018_19 nvarchar(max),pcl_2019_20 nvarchar(max),drinking_water_quality_compliance nvarchar(max),water_quality_contacts nvarchar(max),supply_interruptions_3_hours nvarchar(max),pollution_incidents_cat_3 nvarchar(max),internal_sewer_flooding nvarchar(max),scheme_specific_factor nvarchar(max),asset_health nvarchar(max),nep nvarchar(max),aim nvarchar(max),no_of_sub_measures int,financial_odi_2015_16 nvarchar(max),financial_odi_2016_17 nvarchar(max),financial_odi_2017_18 nvarchar(max),financial_odi_2018_19 nvarchar(max),financial_odi_2019_20 nvarchar(max),underp_payment_collar_2015_16 nvarchar(max),underp_payment_collar_2016_17 nvarchar(max),underp_payment_collar_2017_18 nvarchar(max),underp_payment_collar_2018_19 nvarchar(max),underp_payment_collar_2019_20 nvarchar(max),underp_payment_deadband_2015_16 nvarchar(max),underp_payment_deadband_2016_17 nvarchar(max),underp_payment_deadband_2017_18 nvarchar(max),underp_payment_deadband_2018_19 nvarchar(max),underp_payment_deadband_2019_20 nvarchar(max),outp_payment_deadband_2015_16 nvarchar(max),outp_payment_deadband_2016_17 nvarchar(max),outp_payment_deadband_2017_18 nvarchar(max),outp_payment_deadband_2018_19 nvarchar(max),outp_payment_deadband_2019_20 nvarchar(max),outp_payment_cap_2015_16 nvarchar(max),outp_payment_cap_2016_17 nvarchar(max),outp_payment_cap_2017_18 nvarchar(max),outp_payment_cap_2018_19 nvarchar(max),outp_payment_cap_2019_20 nvarchar(max),underp_payment1_incentive_rate_gbpm nvarchar(max),underp_payment2_incentive_rate_gbpm nvarchar(max),underp_payment3_incentive_rate_gbpm nvarchar(max),underp_payment4_incentive_rate_gbpm nvarchar(max),outp_payment1_incentive_rate_gbpm nvarchar(max),outp_payment2_incentive_rate_gbpm nvarchar(max),standard_odi_operand float,standard_odi_operand_note nvarchar(max),performance_level_actual_2014_15 nvarchar(max),performance_level_actual_2015_16 nvarchar(max),pcl_met_2015_16 nvarchar(max),outp_payment_or_underp_payment_in_period_odis_2015_16 nvarchar(max),outp_payment_or_underp_payment_in_period_odis_gbpm_2015_16 nvarchar(max),notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_2015_16 nvarchar(max),notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_gbpm_2015_16 nvarchar(max),total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2015_16 nvarchar(max),total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2015_16 nvarchar(max),performance_level_actual_2016_17 nvarchar(max),pcl_met_2016_17 nvarchar(max),outp_payment_or_underp_payment_in_period_odis_2016_17 nvarchar(max),outp_payment_or_underp_payment_in_period_odis_gbpm_2016_17 nvarchar(max),notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_2016_17 nvarchar(max),notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_gbpm_2016_17 nvarchar(max),total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2016_17 nvarchar(max),total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2016_17 nvarchar(max),performance_level_actual_2017_18 nvarchar(max),pcl_met_2017_18 nvarchar(max),outp_payment_or_underp_payment_in_period_odis_2017_18 nvarchar(max),outp_payment_or_underp_payment_in_period_odis_gbpm_2017_18 nvarchar(max),notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_2017_18 nvarchar(max),notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_gbpm_2017_18 nvarchar(max),total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2017_18 nvarchar(max),total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2017_18 nvarchar(max),performance_level_actual_2018_19 nvarchar(max),pcl_met_2018_19 nvarchar(max),outp_payment_or_underp_payment_in_period_odis_2018_19 nvarchar(max),outp_payment_or_underp_payment_in_period_odis_gbpm_2018_19 nvarchar(max),notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_2018_19 nvarchar(max),notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_gbpm_2018_19 nvarchar(max),total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2018_19 nvarchar(max),total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2018_19 nvarchar(max),performance_level_actual_2019_20 nvarchar(max),pcl_met_2019_20 nvarchar(max),outp_payment_or_underp_payment_in_period_odis_2019_20 nvarchar(max),outp_payment_or_underp_payment_in_period_odis_gbpm_2019_20 nvarchar(max),notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_2019_20 nvarchar(max),notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_2019_20 nvarchar(max),performance_level_actual_estimates_2019_20 nvarchar(max),pcl_met_estimates_2019_20 nvarchar(max),outp_payment_or_underp_payment_in_period_odis_estimates_2019_20 nvarchar(max),outp_payment_or_underp_payment_in_period_odis_gbpm_estimates_2019_20 nvarchar(max),notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_estimates_2019_20 nvarchar(max),notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_estimates_2019_20 nvarchar(max),price_control_allocation_water_resources float,price_control_allocation_water_network_plus float,price_control_allocation_wastewater_network_plus float,price_control_allocation_bioresources_sludge float,price_control_allocation_residential_retail float,price_control_allocation_business_retail float,price_control_allocation_direct_procurement_for_customers float,price_control_allocation_dummy_control float,isnumeric_underp_payment1_incentive_rate_gbpm BIT, isnumeric_underp_payment2_incentive_rate_gbpm BIT,isnumeric_underp_payment3_incentive_rate_gbpm BIT, isnumeric_underp_payment4_incentive_rate_gbpm BIT,isnumeric_outp_payment1_incentive_rate_gbpm BIT, isnumeric_outp_payment2_incentive_rate_gbpm BIT,onlynumeric_underp_payment1_incentive_rate_gbpm float, onlynumeric_underp_payment2_incentive_rate_gbpm float,onlynumeric_underp_payment3_incentive_rate_gbpm float, onlynumeric_underp_payment4_incentive_rate_gbpm float,onlynumeric_outp_payment1_incentive_rate_gbpm float, onlynumeric_outp_payment2_incentive_rate_gbpm float)')
        for row in df.itertuples():
            cursor.execute('''
            INSERT INTO ''' + schemanameused + '''.PR14FinalCSVcreatedbyPython (unique_id,company_type,company,element_name,element_acronym,outcome,pc_ref,annex,performance_commitment,odi_type,odi_form,in_period_odi,vanilla_odi,primary_category,pc_unit,pc_unit_description,decimal_places,direction_of_improving_performance,starting_level_pr14_fd_2014_15,pcl_2015_16,pcl_2016_17,pcl_2017_18,pcl_2018_19,pcl_2019_20,drinking_water_quality_compliance,water_quality_contacts,supply_interruptions_3_hours,pollution_incidents_cat_3,internal_sewer_flooding,scheme_specific_factor,asset_health,nep,aim,no_of_sub_measures,financial_odi_2015_16,financial_odi_2016_17,financial_odi_2017_18,financial_odi_2018_19,financial_odi_2019_20,underp_payment_collar_2015_16,underp_payment_collar_2016_17,underp_payment_collar_2017_18,underp_payment_collar_2018_19,underp_payment_collar_2019_20,underp_payment_deadband_2015_16,underp_payment_deadband_2016_17,underp_payment_deadband_2017_18,underp_payment_deadband_2018_19,underp_payment_deadband_2019_20,outp_payment_deadband_2015_16,outp_payment_deadband_2016_17,outp_payment_deadband_2017_18,outp_payment_deadband_2018_19,outp_payment_deadband_2019_20,outp_payment_cap_2015_16,outp_payment_cap_2016_17,outp_payment_cap_2017_18,outp_payment_cap_2018_19,outp_payment_cap_2019_20,underp_payment1_incentive_rate_gbpm,underp_payment2_incentive_rate_gbpm,underp_payment3_incentive_rate_gbpm,underp_payment4_incentive_rate_gbpm,outp_payment1_incentive_rate_gbpm,outp_payment2_incentive_rate_gbpm,standard_odi_operand,standard_odi_operand_note,performance_level_actual_2014_15,performance_level_actual_2015_16,pcl_met_2015_16,outp_payment_or_underp_payment_in_period_odis_2015_16,outp_payment_or_underp_payment_in_period_odis_gbpm_2015_16,notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_2015_16,notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_gbpm_2015_16,total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2015_16,total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2015_16,performance_level_actual_2016_17,pcl_met_2016_17,outp_payment_or_underp_payment_in_period_odis_2016_17,outp_payment_or_underp_payment_in_period_odis_gbpm_2016_17,notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_2016_17,notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_gbpm_2016_17,total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2016_17,total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2016_17,performance_level_actual_2017_18,pcl_met_2017_18,outp_payment_or_underp_payment_in_period_odis_2017_18,outp_payment_or_underp_payment_in_period_odis_gbpm_2017_18,notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_2017_18,notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_gbpm_2017_18,total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2017_18,total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2017_18,performance_level_actual_2018_19,pcl_met_2018_19,outp_payment_or_underp_payment_in_period_odis_2018_19,outp_payment_or_underp_payment_in_period_odis_gbpm_2018_19,notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_2018_19,notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_gbpm_2018_19,total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2018_19,total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2018_19,performance_level_actual_2019_20,pcl_met_2019_20,outp_payment_or_underp_payment_in_period_odis_2019_20,outp_payment_or_underp_payment_in_period_odis_gbpm_2019_20,notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_2019_20,notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_2019_20,performance_level_actual_estimates_2019_20,pcl_met_estimates_2019_20,outp_payment_or_underp_payment_in_period_odis_estimates_2019_20,outp_payment_or_underp_payment_in_period_odis_gbpm_estimates_2019_20,notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_estimates_2019_20,notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_estimates_2019_20,price_control_allocation_water_resources,price_control_allocation_water_network_plus,price_control_allocation_wastewater_network_plus,price_control_allocation_bioresources_sludge,price_control_allocation_residential_retail,price_control_allocation_business_retail,price_control_allocation_direct_procurement_for_customers,price_control_allocation_dummy_control,isnumeric_underp_payment1_incentive_rate_gbpm, isnumeric_underp_payment2_incentive_rate_gbpm,isnumeric_underp_payment3_incentive_rate_gbpm, isnumeric_underp_payment4_incentive_rate_gbpm,isnumeric_outp_payment1_incentive_rate_gbpm, isnumeric_outp_payment2_incentive_rate_gbpm,onlynumeric_underp_payment1_incentive_rate_gbpm, onlynumeric_underp_payment2_incentive_rate_gbpm,onlynumeric_underp_payment3_incentive_rate_gbpm, onlynumeric_underp_payment4_incentive_rate_gbpm,onlynumeric_outp_payment1_incentive_rate_gbpm, onlynumeric_outp_payment2_incentive_rate_gbpm)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ''',
                           row.unique_id,
                           row.company_type,
                           row.company,
                           row.element_name,
                           row.element_acronym,
                           row.outcome,
                           row.pc_ref,
                           row.annex,
                           row.performance_commitment,
                           row.odi_type,
                           row.odi_form,
                           row.in_period_odi,
                           row.vanilla_odi,
                           row.primary_category,
                           row.pc_unit,
                           row.pc_unit_description,
                           row.decimal_places,
                           row.direction_of_improving_performance,
                           row.starting_level_pr14_fd_2014_15,
                           row.pcl_2015_16,
                           row.pcl_2016_17,
                           row.pcl_2017_18,
                           row.pcl_2018_19,
                           row.pcl_2019_20,
                           row.drinking_water_quality_compliance,
                           row.water_quality_contacts,
                           row.supply_interruptions_3_hours,
                           row.pollution_incidents_cat_3,
                           row.internal_sewer_flooding,
                           row.scheme_specific_factor,
                           row.asset_health,
                           row.nep,
                           row.aim,
                           row.no_of_sub_measures,
                           row.financial_odi_2015_16,
                           row.financial_odi_2016_17,
                           row.financial_odi_2017_18,
                           row.financial_odi_2018_19,
                           row.financial_odi_2019_20,
                           row.underp_payment_collar_2015_16,
                           row.underp_payment_collar_2016_17,
                           row.underp_payment_collar_2017_18,
                           row.underp_payment_collar_2018_19,
                           row.underp_payment_collar_2019_20,
                           row.underp_payment_deadband_2015_16,
                           row.underp_payment_deadband_2016_17,
                           row.underp_payment_deadband_2017_18,
                           row.underp_payment_deadband_2018_19,
                           row.underp_payment_deadband_2019_20,
                           row.outp_payment_deadband_2015_16,
                           row.outp_payment_deadband_2016_17,
                           row.outp_payment_deadband_2017_18,
                           row.outp_payment_deadband_2018_19,
                           row.outp_payment_deadband_2019_20,
                           row.outp_payment_cap_2015_16,
                           row.outp_payment_cap_2016_17,
                           row.outp_payment_cap_2017_18,
                           row.outp_payment_cap_2018_19,
                           row.outp_payment_cap_2019_20,
                           row.underp_payment1_incentive_rate_gbpm,
                           row.underp_payment2_incentive_rate_gbpm,
                           row.underp_payment3_incentive_rate_gbpm,
                           row.underp_payment4_incentive_rate_gbpm,
                           row.outp_payment1_incentive_rate_gbpm,
                           row.outp_payment2_incentive_rate_gbpm,
                           row.standard_odi_operand,
                           row.standard_odi_operand_note,
                           row.performance_level_actual_2014_15,
                           row.performance_level_actual_2015_16,
                           row.pcl_met_2015_16,
                           row.outp_payment_or_underp_payment_in_period_odis_2015_16,
                           row.outp_payment_or_underp_payment_in_period_odis_gbpm_2015_16,
                           row.notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_2015_16,
                           row.notional_outp_payment_or_underp_payment_accrued_at_31_march_2016_gbpm_2015_16,
                           row.total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2015_16,
                           row.total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2015_16,
                           row.performance_level_actual_2016_17,
                           row.pcl_met_2016_17,
                           row.outp_payment_or_underp_payment_in_period_odis_2016_17,
                           row.outp_payment_or_underp_payment_in_period_odis_gbpm_2016_17,
                           row.notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_2016_17,
                           row.notional_outp_payment_or_underp_payment_accrued_at_31_march_2017_gbpm_2016_17,
                           row.total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2016_17,
                           row.total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2016_17,
                           row.performance_level_actual_2017_18,
                           row.pcl_met_2017_18,
                           row.outp_payment_or_underp_payment_in_period_odis_2017_18,
                           row.outp_payment_or_underp_payment_in_period_odis_gbpm_2017_18,
                           row.notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_2017_18,
                           row.notional_outp_payment_or_underp_payment_accrued_at_31_march_2018_gbpm_2017_18,
                           row.total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2017_18,
                           row.total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2017_18,
                           row.performance_level_actual_2018_19,
                           row.pcl_met_2018_19,
                           row.outp_payment_or_underp_payment_in_period_odis_2018_19,
                           row.outp_payment_or_underp_payment_in_period_odis_gbpm_2018_19,
                           row.notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_2018_19,
                           row.notional_outp_payment_or_underp_payment_accrued_at_31_march_2019_gbpm_2018_19,
                           row.total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_2018_19,
                           row.total_amp6_outp_payment_or_underp_payment_31_march_2020_forecast_gbpm_2018_19,
                           row.performance_level_actual_2019_20,
                           row.pcl_met_2019_20,
                           row.outp_payment_or_underp_payment_in_period_odis_2019_20,
                           row.outp_payment_or_underp_payment_in_period_odis_gbpm_2019_20,
                           row.notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_2019_20,
                           row.notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_2019_20,
                           row.performance_level_actual_estimates_2019_20,
                           row.pcl_met_estimates_2019_20,
                           row.outp_payment_or_underp_payment_in_period_odis_estimates_2019_20,
                           row.outp_payment_or_underp_payment_in_period_odis_gbpm_estimates_2019_20,
                           row.notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_estimates_2019_20,
                           row.notional_outp_payment_or_underp_payment_accrued_at_31_march_2020_gbpm_estimates_2019_20,
                           row.price_control_allocation_water_resources,
                           row.price_control_allocation_water_network_plus,
                           row.price_control_allocation_wastewater_network_plus,
                           row.price_control_allocation_bioresources_sludge,
                           row.price_control_allocation_residential_retail,
                           row.price_control_allocation_business_retail,
                           row.price_control_allocation_direct_procurement_for_customers,
                           row.price_control_allocation_dummy_control,
                           row.isnumeric_underp_payment1_incentive_rate_gbpm,
                           row.isnumeric_underp_payment2_incentive_rate_gbpm,
                           row.isnumeric_underp_payment3_incentive_rate_gbpm,
                           row.isnumeric_underp_payment4_incentive_rate_gbpm,
                           row.isnumeric_outp_payment1_incentive_rate_gbpm,
                           row.isnumeric_outp_payment2_incentive_rate_gbpm,
                           row.onlynumeric_underp_payment1_incentive_rate_gbpm,
                           row.onlynumeric_underp_payment2_incentive_rate_gbpm,
                           row.onlynumeric_underp_payment3_incentive_rate_gbpm,
                           row.onlynumeric_underp_payment4_incentive_rate_gbpm,
                           row.onlynumeric_outp_payment1_incentive_rate_gbpm,
                           row.onlynumeric_outp_payment2_incentive_rate_gbpm
                           )
    else:
        print("PR14FinalCSVcreatedbyPython table is present")

    # Query for PR19 data upload
    cursor.execute(
        "SELECT * FROM information_schema.tables where table_schema ='" + schemanameused + "' and table_name = 'PR19FinalCSVcreatedbyPython'")
    queryforsubmeasuretablecheck = cursor.fetchone()
    if queryforsubmeasuretablecheck == None:
        print("Creating PR19FinalCSVcreatedbyPython table")
        cursor.execute(
            'CREATE TABLE ' + schemanameused + '.PR19FinalCSVcreatedbyPython (company nvarchar(max),unique_id nvarchar(max),outcome nvarchar(max),pc_ref nvarchar(max),performance_commitment nvarchar(max),pc_short_description nvarchar(max),price_control_allocation_water_resources float,price_control_allocation_water_network_plus float,price_control_allocation_wastewater_network_plus float,price_control_allocation_bioresources_sludge float,price_control_allocation_residential_retail float,price_control_allocation_business_retail float,price_control_allocation_direct_procurement_for_customers float,price_control_allocation_dummy_control float,odi_type nvarchar(max),odi_form nvarchar(max),odi_timing nvarchar(max),primary_category nvarchar(max),pc_unit nvarchar(max),pc_unit_description nvarchar(max),decimal_places nvarchar(max),direction_of_improving_performance nvarchar(max),common_and_comparable_bespoke_performance_commitment nvarchar(max),special_cost_factor nvarchar(max),scheme_specific_factor nvarchar(max),asset_health nvarchar(max),nep nvarchar(max),aim nvarchar(max),customers_relative_priority nvarchar(max),pcl_2020_21 nvarchar(max),pcl_2021_22 nvarchar(max),pcl_2022_23 nvarchar(max),pcl_2023_24 nvarchar(max),pcl_2024_25 nvarchar(max),financial_odi_2020_21 nvarchar(max),financial_odi_2021_22 nvarchar(max),financial_odi_2022_23 nvarchar(max),financial_odi_2023_24 nvarchar(max),financial_odi_2024_25 nvarchar(max),enhanced_underp_payment_collar_2020_21 nvarchar(max),enhanced_underp_payment_collar_2021_22 nvarchar(max),enhanced_underp_payment_collar_2022_23 nvarchar(max),enhanced_underp_payment_collar_2023_24 nvarchar(max),enhanced_underp_payment_collar_2024_25 nvarchar(max),standard_underp_payment_collar_2020_21 nvarchar(max),standard_underp_payment_collar_2021_22 nvarchar(max),standard_underp_payment_collar_2022_23 nvarchar(max),standard_underp_payment_collar_2023_24 nvarchar(max),standard_underp_payment_collar_2024_25 nvarchar(max),underp_payment_deadband_2020_21 nvarchar(max),underp_payment_deadband_2021_22 nvarchar(max),underp_payment_deadband_2022_23 nvarchar(max),underp_payment_deadband_2023_24 nvarchar(max),underp_payment_deadband_2024_25 nvarchar(max),outp_payment_deadband_2020_21 nvarchar(max),outp_payment_deadband_2021_22 nvarchar(max),outp_payment_deadband_2022_23 nvarchar(max),outp_payment_deadband_2023_24 nvarchar(max),outp_payment_deadband_2024_25 nvarchar(max),standard_outp_payment_cap_2020_21 nvarchar(max),standard_outp_payment_cap_2021_22 nvarchar(max),standard_outp_payment_cap_2022_23 nvarchar(max),standard_outp_payment_cap_2023_24 nvarchar(max),standard_outp_payment_cap_2024_25 nvarchar(max),enhanced_outp_payment_cap_2020_21 nvarchar(max),enhanced_outp_payment_cap_2021_22 nvarchar(max),enhanced_outp_payment_cap_2022_23 nvarchar(max),enhanced_outp_payment_cap_2023_24 nvarchar(max),enhanced_outp_payment_cap_2024_25 nvarchar(max),underp_payment_incentive_standard_underp_payment1_tier2_where_tiers_apply nvarchar(max),underp_payment_incentive_standard_underp_payment2_tier1_where_tiers_apply nvarchar(max),underp_payment_incentive_standard_underp_payment3_tier3_where_tiers_apply nvarchar(max),underp_payment_incentive_enhanced_underp_payment nvarchar(max),outp_payment_incentive_standard_outp_payment1_tier2_where_tiers_apply nvarchar(max),outp_payment_incentive_standard_outp_payment2_tier1_where_tiers_apply nvarchar(max),outp_payment_incentive_standard_outp_payment3_tier3_where_tiers_apply nvarchar(max),outp_payment_incentive_enhanced_outp_payment nvarchar(max),standard_odi_cal nvarchar(max),standard_odi_operand float,standard_odi_operand_note nvarchar(max),isnumeric_underp_payment_incentive_standard_underp_payment1_tier2_where_tiers_apply BIT,onlynumeric_underp_payment_incentive_standard_underp_payment1_tier2_where_tiers_apply float,isnumeric_underp_payment_incentive_standard_underp_payment2_tier1_where_tiers_apply BIT,onlynumeric_underp_payment_incentive_standard_underp_payment2_tier1_where_tiers_apply float,isnumeric_underp_payment_incentive_standard_underp_payment3_tier3_where_tiers_apply BIT,onlynumeric_underp_payment_incentive_standard_underp_payment3_tier3_where_tiers_apply float,isnumeric_underp_payment_incentive_enhanced_underp_payment BIT,onlynumeric_underp_payment_incentive_enhanced_underp_payment float,isnumeric_outp_payment_incentive_standard_outp_payment1_tier2_where_tiers_apply BIT,onlynumeric_outp_payment_incentive_standard_outp_payment1_tier2_where_tiers_apply float,isnumeric_outp_payment_incentive_standard_outp_payment2_tier1_where_tiers_apply BIT,onlynumeric_outp_payment_incentive_standard_outp_payment2_tier1_where_tiers_apply float,isnumeric_outp_payment_incentive_standard_outp_payment3_tier3_where_tiers_apply BIT,onlynumeric_outp_payment_incentive_standard_outp_payment3_tier3_where_tiers_apply float,isnumeric_outp_payment_incentive_enhanced_outp_payment BIT,onlynumeric_outp_payment_incentive_enhanced_outp_payment float)')
        for row in df1.itertuples():
            cursor.execute('''
            INSERT INTO ''' + schemanameused + '''.PR19FinalCSVcreatedbyPython (company,unique_id,outcome,pc_ref,performance_commitment,pc_short_description,price_control_allocation_water_resources,price_control_allocation_water_network_plus,price_control_allocation_wastewater_network_plus,price_control_allocation_bioresources_sludge,price_control_allocation_residential_retail,price_control_allocation_business_retail,price_control_allocation_direct_procurement_for_customers,price_control_allocation_dummy_control,odi_type,odi_form,odi_timing,primary_category,pc_unit,pc_unit_description,decimal_places,direction_of_improving_performance,common_and_comparable_bespoke_performance_commitment,special_cost_factor,scheme_specific_factor,asset_health,nep,aim,customers_relative_priority,pcl_2020_21,pcl_2021_22,pcl_2022_23,pcl_2023_24,pcl_2024_25,financial_odi_2020_21,financial_odi_2021_22,financial_odi_2022_23,financial_odi_2023_24,financial_odi_2024_25,enhanced_underp_payment_collar_2020_21,enhanced_underp_payment_collar_2021_22,enhanced_underp_payment_collar_2022_23,enhanced_underp_payment_collar_2023_24,enhanced_underp_payment_collar_2024_25,standard_underp_payment_collar_2020_21,standard_underp_payment_collar_2021_22,standard_underp_payment_collar_2022_23,standard_underp_payment_collar_2023_24,standard_underp_payment_collar_2024_25,underp_payment_deadband_2020_21,underp_payment_deadband_2021_22,underp_payment_deadband_2022_23,underp_payment_deadband_2023_24,underp_payment_deadband_2024_25,outp_payment_deadband_2020_21,outp_payment_deadband_2021_22,outp_payment_deadband_2022_23,outp_payment_deadband_2023_24,outp_payment_deadband_2024_25,standard_outp_payment_cap_2020_21,standard_outp_payment_cap_2021_22,standard_outp_payment_cap_2022_23,standard_outp_payment_cap_2023_24,standard_outp_payment_cap_2024_25,enhanced_outp_payment_cap_2020_21,enhanced_outp_payment_cap_2021_22,enhanced_outp_payment_cap_2022_23,enhanced_outp_payment_cap_2023_24,enhanced_outp_payment_cap_2024_25,underp_payment_incentive_standard_underp_payment1_tier2_where_tiers_apply,underp_payment_incentive_standard_underp_payment2_tier1_where_tiers_apply,underp_payment_incentive_standard_underp_payment3_tier3_where_tiers_apply,underp_payment_incentive_enhanced_underp_payment,outp_payment_incentive_standard_outp_payment1_tier2_where_tiers_apply,outp_payment_incentive_standard_outp_payment2_tier1_where_tiers_apply,outp_payment_incentive_standard_outp_payment3_tier3_where_tiers_apply,outp_payment_incentive_enhanced_outp_payment,standard_odi_cal,standard_odi_operand,standard_odi_operand_note,isnumeric_underp_payment_incentive_standard_underp_payment1_tier2_where_tiers_apply ,onlynumeric_underp_payment_incentive_standard_underp_payment1_tier2_where_tiers_apply ,isnumeric_underp_payment_incentive_standard_underp_payment2_tier1_where_tiers_apply ,onlynumeric_underp_payment_incentive_standard_underp_payment2_tier1_where_tiers_apply ,isnumeric_underp_payment_incentive_standard_underp_payment3_tier3_where_tiers_apply ,onlynumeric_underp_payment_incentive_standard_underp_payment3_tier3_where_tiers_apply ,isnumeric_underp_payment_incentive_enhanced_underp_payment ,onlynumeric_underp_payment_incentive_enhanced_underp_payment ,isnumeric_outp_payment_incentive_standard_outp_payment1_tier2_where_tiers_apply ,onlynumeric_outp_payment_incentive_standard_outp_payment1_tier2_where_tiers_apply ,isnumeric_outp_payment_incentive_standard_outp_payment2_tier1_where_tiers_apply ,onlynumeric_outp_payment_incentive_standard_outp_payment2_tier1_where_tiers_apply ,isnumeric_outp_payment_incentive_standard_outp_payment3_tier3_where_tiers_apply ,onlynumeric_outp_payment_incentive_standard_outp_payment3_tier3_where_tiers_apply ,isnumeric_outp_payment_incentive_enhanced_outp_payment ,onlynumeric_outp_payment_incentive_enhanced_outp_payment)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ''',
                           row.company,
                           row.unique_id,
                           row.outcome,
                           row.pc_ref,
                           row.performance_commitment,
                           row.pc_short_description,
                           row.price_control_allocation_water_resources,
                           row.price_control_allocation_water_network_plus,
                           row.price_control_allocation_wastewater_network_plus,
                           row.price_control_allocation_bioresources_sludge,
                           row.price_control_allocation_residential_retail,
                           row.price_control_allocation_business_retail,
                           row.price_control_allocation_direct_procurement_for_customers,
                           row.price_control_allocation_dummy_control,
                           row.odi_type,
                           row.odi_form,
                           row.odi_timing,
                           row.primary_category,
                           row.pc_unit,
                           row.pc_unit_description,
                           row.decimal_places,
                           row.direction_of_improving_performance,
                           row.common_and_comparable_bespoke_performance_commitment,
                           row.special_cost_factor,
                           row.scheme_specific_factor,
                           row.asset_health,
                           row.nep,
                           row.aim,
                           row.customers_relative_priority,
                           row.pcl_2020_21,
                           row.pcl_2021_22,
                           row.pcl_2022_23,
                           row.pcl_2023_24,
                           row.pcl_2024_25,
                           row.financial_odi_2020_21,
                           row.financial_odi_2021_22,
                           row.financial_odi_2022_23,
                           row.financial_odi_2023_24,
                           row.financial_odi_2024_25,
                           row.enhanced_underp_payment_collar_2020_21,
                           row.enhanced_underp_payment_collar_2021_22,
                           row.enhanced_underp_payment_collar_2022_23,
                           row.enhanced_underp_payment_collar_2023_24,
                           row.enhanced_underp_payment_collar_2024_25,
                           row.standard_underp_payment_collar_2020_21,
                           row.standard_underp_payment_collar_2021_22,
                           row.standard_underp_payment_collar_2022_23,
                           row.standard_underp_payment_collar_2023_24,
                           row.standard_underp_payment_collar_2024_25,
                           row.underp_payment_deadband_2020_21,
                           row.underp_payment_deadband_2021_22,
                           row.underp_payment_deadband_2022_23,
                           row.underp_payment_deadband_2023_24,
                           row.underp_payment_deadband_2024_25,
                           row.outp_payment_deadband_2020_21,
                           row.outp_payment_deadband_2021_22,
                           row.outp_payment_deadband_2022_23,
                           row.outp_payment_deadband_2023_24,
                           row.outp_payment_deadband_2024_25,
                           row.standard_outp_payment_cap_2020_21,
                           row.standard_outp_payment_cap_2021_22,
                           row.standard_outp_payment_cap_2022_23,
                           row.standard_outp_payment_cap_2023_24,
                           row.standard_outp_payment_cap_2024_25,
                           row.enhanced_outp_payment_cap_2020_21,
                           row.enhanced_outp_payment_cap_2021_22,
                           row.enhanced_outp_payment_cap_2022_23,
                           row.enhanced_outp_payment_cap_2023_24,
                           row.enhanced_outp_payment_cap_2024_25,
                           row.underp_payment_incentive_standard_underp_payment1_tier2_where_tiers_apply,
                           row.underp_payment_incentive_standard_underp_payment2_tier1_where_tiers_apply,
                           row.underp_payment_incentive_standard_underp_payment3_tier3_where_tiers_apply,
                           row.underp_payment_incentive_enhanced_underp_payment,
                           row.outp_payment_incentive_standard_outp_payment1_tier2_where_tiers_apply,
                           row.outp_payment_incentive_standard_outp_payment2_tier1_where_tiers_apply,
                           row.outp_payment_incentive_standard_outp_payment3_tier3_where_tiers_apply,
                           row.outp_payment_incentive_enhanced_outp_payment,
                           row.standard_odi_cal,
                           row.standard_odi_operand,
                           row.standard_odi_operand_note,
                           row.isnumeric_underp_payment_incentive_standard_underp_payment1_tier2_where_tiers_apply,
                           row.onlynumeric_underp_payment_incentive_standard_underp_payment1_tier2_where_tiers_apply,
                           row.isnumeric_underp_payment_incentive_standard_underp_payment2_tier1_where_tiers_apply,
                           row.onlynumeric_underp_payment_incentive_standard_underp_payment2_tier1_where_tiers_apply,
                           row.isnumeric_underp_payment_incentive_standard_underp_payment3_tier3_where_tiers_apply,
                           row.onlynumeric_underp_payment_incentive_standard_underp_payment3_tier3_where_tiers_apply,
                           row.isnumeric_underp_payment_incentive_enhanced_underp_payment,
                           row.onlynumeric_underp_payment_incentive_enhanced_underp_payment,
                           row.isnumeric_outp_payment_incentive_standard_outp_payment1_tier2_where_tiers_apply,
                           row.onlynumeric_outp_payment_incentive_standard_outp_payment1_tier2_where_tiers_apply,
                           row.isnumeric_outp_payment_incentive_standard_outp_payment2_tier1_where_tiers_apply,
                           row.onlynumeric_outp_payment_incentive_standard_outp_payment2_tier1_where_tiers_apply,
                           row.isnumeric_outp_payment_incentive_standard_outp_payment3_tier3_where_tiers_apply,
                           row.onlynumeric_outp_payment_incentive_standard_outp_payment3_tier3_where_tiers_apply,
                           row.isnumeric_outp_payment_incentive_enhanced_outp_payment,
                           row.onlynumeric_outp_payment_incentive_enhanced_outp_payment
                           )
    else:
        print("PR19FinalCSVcreatedbyPython table is present")

    # Query for PR14 submeasure upload
    cursor.execute(
        "SELECT * FROM information_schema.tables where table_schema ='" + schemanameused + "' and table_name = 'PR14SubmeasureFinalCSVcreatedbyPython'")
    queryforsubmeasuretablecheck = cursor.fetchone()
    if queryforsubmeasuretablecheck == None:
        print("Creating PR14SubmeasureFinalCSVcreatedbyPython table")
        cursor.execute(
            'CREATE TABLE ' + schemanameused + '.PR14SubmeasureFinalCSVcreatedbyPython(unique_id nvarchar(max),company_type nvarchar(max),company nvarchar(max),element_acronym nvarchar(max),pc_ref nvarchar(max),performance_commitment nvarchar(max),odi_type nvarchar(max),primary_category nvarchar(max),pc_unit_description nvarchar(max),starting_level_pr14_fd_2014_15 nvarchar(max),pcl_2015_16 nvarchar(max),pcl_2016_17 nvarchar(max),pcl_2017_18 nvarchar(max),pcl_2018_19 nvarchar(max),pcl_2019_20 nvarchar(max),sub_measure_id nvarchar(max),sub_measure nvarchar(max),sub_measure_category nvarchar(max),sub_measure_weighting nvarchar(max),pc_unit nvarchar(max),decimal_places nvarchar(max),submeasure_performace_level_reference_regulatory_output_during_2010_15 nvarchar(max),submeasure_performace_level_reference_expected_performance_by_2014_15 nvarchar(max),submeasure_performace_level_2015_16 nvarchar(max),submeasure_performace_level_2016_17 nvarchar(max),submeasure_performace_level_2017_18 nvarchar(max),submeasure_performace_level_2018_19 nvarchar(max),submeasure_performace_level_2019_20 nvarchar(max),submeasure_high_reference_regulatory_output_during_2010_15 nvarchar(max),submeasure_high_reference_expected_performance_by_2014_15 nvarchar(max),submeasure_high_2015_16 nvarchar(max),submeasure_high_2016_17 nvarchar(max),submeasure_high_2017_18 nvarchar(max),submeasure_high_2018_19 nvarchar(max),submeasure_high_2019_20 nvarchar(max),submeasure_low_reference_regulatory_output_during_2010_15 float,submeasure_low_reference_expected_performance_by_2014_15 float,submeasure_low_2015_16 nvarchar(max),submeasure_low_2016_17 nvarchar(max),submeasure_low_2017_18 nvarchar(max),submeasure_low_2018_19 nvarchar(max),submeasure_low_2019_20 nvarchar(max),failure_threshold_for_AMP6 nvarchar(max),actual_performance_level_pcs_submeasures_actual_2014_15 nvarchar(max),actual_performance_level_pcs_submeasures_actual_2015_16 nvarchar(max),actual_performance_level_pcs_submeasures_pcl_met_2015_16 nvarchar(max),actual_performance_level_pcs_submeasures_actual_2016_17 nvarchar(max),actual_performance_level_pcs_submeasures_pcl_met_2016_17 nvarchar(max),actual_performance_level_pcs_submeasures_actual_2017_18 nvarchar(max),actual_performance_level_pcs_submeasures_pcl_met_2017_18 nvarchar(max),actual_performance_level_pcs_submeasures_actual_2018_19 nvarchar(max),actual_performance_level_pcs_submeasures_pcl_met_2018_19 nvarchar(max),actual_performance_level_pcs_submeasures_actual_2019_20 nvarchar(max),actual_performance_level_pcs_submeasures_pcl_met_2019_20 nvarchar(max),actual_performance_level_pcs_submeasures_actual_estimate_2019_20 nvarchar(max),actual_performance_level_pcs_submeasures_pcl_met_estimate_2019_20 nvarchar(max),direction_of_improving_performance nvarchar(max),comms_filter nvarchar(max),actual_performance_compared_with_previous_actual_performance_2014_15_to_2015_16 nvarchar(max),actual_performance_compared_with_previous_actual_performance_2015_16_to_2016_17 nvarchar(max),actual_performance_compared_with_previous_actual_performance_2016_17_to_2017_18 nvarchar(max),actual_performance_compared_with_previous_actual_performance_2017_18_to_2018_19 nvarchar(max),actual_performance_compared_with_previous_actual_performance_2018_19_to_2019_20 nvarchar(max),actual_performance_compared_with_previous_actual_performance_2014_15_to_2016_17_amp_so_far nvarchar(max))')
        for row in df2.itertuples():
            cursor.execute('''
            INSERT INTO ''' + schemanameused + '''.PR14SubmeasureFinalCSVcreatedbyPython (unique_id,company_type,company,element_acronym,pc_ref,performance_commitment,odi_type,primary_category,pc_unit_description,starting_level_pr14_fd_2014_15,pcl_2015_16,pcl_2016_17,pcl_2017_18,pcl_2018_19,pcl_2019_20,sub_measure_id,sub_measure,sub_measure_category,sub_measure_weighting,pc_unit,decimal_places,submeasure_performace_level_reference_regulatory_output_during_2010_15,submeasure_performace_level_reference_expected_performance_by_2014_15,submeasure_performace_level_2015_16,submeasure_performace_level_2016_17,submeasure_performace_level_2017_18,submeasure_performace_level_2018_19,submeasure_performace_level_2019_20,submeasure_high_reference_regulatory_output_during_2010_15,submeasure_high_reference_expected_performance_by_2014_15,submeasure_high_2015_16,submeasure_high_2016_17,submeasure_high_2017_18,submeasure_high_2018_19,submeasure_high_2019_20,submeasure_low_reference_regulatory_output_during_2010_15,submeasure_low_reference_expected_performance_by_2014_15,submeasure_low_2015_16,submeasure_low_2016_17,submeasure_low_2017_18,submeasure_low_2018_19,submeasure_low_2019_20,failure_threshold_for_AMP6,actual_performance_level_pcs_submeasures_actual_2014_15,actual_performance_level_pcs_submeasures_actual_2015_16,actual_performance_level_pcs_submeasures_pcl_met_2015_16,actual_performance_level_pcs_submeasures_actual_2016_17,actual_performance_level_pcs_submeasures_pcl_met_2016_17,actual_performance_level_pcs_submeasures_actual_2017_18,actual_performance_level_pcs_submeasures_pcl_met_2017_18,actual_performance_level_pcs_submeasures_actual_2018_19,actual_performance_level_pcs_submeasures_pcl_met_2018_19,actual_performance_level_pcs_submeasures_actual_2019_20,actual_performance_level_pcs_submeasures_pcl_met_2019_20,actual_performance_level_pcs_submeasures_actual_estimate_2019_20,actual_performance_level_pcs_submeasures_pcl_met_estimate_2019_20,direction_of_improving_performance,comms_filter,actual_performance_compared_with_previous_actual_performance_2014_15_to_2015_16,actual_performance_compared_with_previous_actual_performance_2015_16_to_2016_17,actual_performance_compared_with_previous_actual_performance_2016_17_to_2017_18,actual_performance_compared_with_previous_actual_performance_2017_18_to_2018_19,actual_performance_compared_with_previous_actual_performance_2018_19_to_2019_20,actual_performance_compared_with_previous_actual_performance_2014_15_to_2016_17_amp_so_far)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ''',
                           row.unique_id,
                           row.company_type,
                           row.company,
                           row.element_acronym,
                           row.pc_ref,
                           row.performance_commitment,
                           row.odi_type,
                           row.primary_category,
                           row.pc_unit_description,
                           row.starting_level_pr14_fd_2014_15,
                           row.pcl_2015_16,
                           row.pcl_2016_17,
                           row.pcl_2017_18,
                           row.pcl_2018_19,
                           row.pcl_2019_20,
                           row.sub_measure_id,
                           row.sub_measure,
                           row.sub_measure_category,
                           row.sub_measure_weighting,
                           row.pc_unit,
                           row.decimal_places,
                           row.submeasure_performace_level_reference_regulatory_output_during_2010_15,
                           row.submeasure_performace_level_reference_expected_performance_by_2014_15,
                           row.submeasure_performace_level_2015_16,
                           row.submeasure_performace_level_2016_17,
                           row.submeasure_performace_level_2017_18,
                           row.submeasure_performace_level_2018_19,
                           row.submeasure_performace_level_2019_20,
                           row.submeasure_high_reference_regulatory_output_during_2010_15,
                           row.submeasure_high_reference_expected_performance_by_2014_15,
                           row.submeasure_high_2015_16,
                           row.submeasure_high_2016_17,
                           row.submeasure_high_2017_18,
                           row.submeasure_high_2018_19,
                           row.submeasure_high_2019_20,
                           row.submeasure_low_reference_regulatory_output_during_2010_15,
                           row.submeasure_low_reference_expected_performance_by_2014_15,
                           row.submeasure_low_2015_16,
                           row.submeasure_low_2016_17,
                           row.submeasure_low_2017_18,
                           row.submeasure_low_2018_19,
                           row.submeasure_low_2019_20,
                           row.failure_threshold_for_AMP6,
                           row.actual_performance_level_pcs_submeasures_actual_2014_15,
                           row.actual_performance_level_pcs_submeasures_actual_2015_16,
                           row.actual_performance_level_pcs_submeasures_pcl_met_2015_16,
                           row.actual_performance_level_pcs_submeasures_actual_2016_17,
                           row.actual_performance_level_pcs_submeasures_pcl_met_2016_17,
                           row.actual_performance_level_pcs_submeasures_actual_2017_18,
                           row.actual_performance_level_pcs_submeasures_pcl_met_2017_18,
                           row.actual_performance_level_pcs_submeasures_actual_2018_19,
                           row.actual_performance_level_pcs_submeasures_pcl_met_2018_19,
                           row.actual_performance_level_pcs_submeasures_actual_2019_20,
                           row.actual_performance_level_pcs_submeasures_pcl_met_2019_20,
                           row.actual_performance_level_pcs_submeasures_actual_estimate_2019_20,
                           row.actual_performance_level_pcs_submeasures_pcl_met_estimate_2019_20,
                           row.direction_of_improving_performance,
                           row.comms_filter,
                           row.actual_performance_compared_with_previous_actual_performance_2014_15_to_2015_16,
                           row.actual_performance_compared_with_previous_actual_performance_2015_16_to_2016_17,
                           row.actual_performance_compared_with_previous_actual_performance_2016_17_to_2017_18,
                           row.actual_performance_compared_with_previous_actual_performance_2017_18_to_2018_19,
                           row.actual_performance_compared_with_previous_actual_performance_2018_19_to_2019_20,
                           row.actual_performance_compared_with_previous_actual_performance_2014_15_to_2016_17_amp_so_far
                           )
    else:
        print("PR14SubmeasureFinalCSVcreatedbyPython table is present")

    conn.commit()
